### ISSUE TITLE
Conflict with image lazy load and SP simple portfolio

### ISSUE THREAD

**Issue by mojeweb** [JoomShaper/helix-ultimate#302] opened 2022-11-30 18:38 UTC
### Steps to reproduce the issue
Make SP simple portfolio page items (menu item). ver 2.0.7
-Layout setings. default
In Helix ultimate 2.0.11 enable Image Lazy Loading

### Expected result
Show SP simple portfolio items in grid.

### Actual result
View is corupted. Items are croped.
Without Lazy loading items show ok. With Casiopea template, items show ok.

### System information (as much as possible)
Joomla 4.2.5
PHP 7.4

**Comment by mi-prakash** [comment] 2022-12-02 05:25
@mojeweb I've tested the issue, so far I haven't found anything.
Can u please share us a video how you get the issue? That will help us understand the problem more clearly

**Comment by mojeweb** [comment] 2022-12-02 10:28
You can see on images. With lazy load on, there is a bug with display. I tested with localhost and production server, with diferent sites, always the same result.
The hight of sp-simpleportfolio-items sp-simpleportfolio-columns-3 shuffle container is calculated wrong.
Sometimes refresh or navigate to other page helps, but when you navigate back to portofilo issue remains.

![spportfolio-bug](https://user-images.githubusercontent.com/45881772/205271073-d4f89c58-d1e0-4e08-87e3-306ff82434dd.jpg)
![spportfolio-off](https://user-images.githubusercontent.com/45881772/205271082-d06ac157-3db6-4266-85b8-8503fb49f2ae.jpg)
![spportfolio-ok](https://user-images.githubusercontent.com/45881772/205271084-e2a01f0e-c357-4575-a232-14f95f5a3de3.jpg)
![spportfolio-on](https://user-images.githubusercontent.com/45881772/205271095-8cf2b026-2318-4129-b4b8-aac4bda32275.jpg)

**Comment by mi-prakash** [comment] 2022-12-05 13:20
Thanks for your feedback. We will investigate on it

**Comment by mi-prakash** [comment] 2023-02-16 05:58
@mojeweb 
Good news. This issue will be fixed on the next update.
thanks for supporting us

**Comment by mi-prakash** [comment] 2023-06-07 05:51
@mojeweb Have you tested this issue with the latest release?? 
Please let us know. If the issue is resolved then we have to close the issue

**Comment by mojeweb** [comment] 2023-06-08 06:06
It is solved.

**Closed** 2023-06-08 06:10 UTC
Labels: pending
