### ISSUE TITLE
Joomla 4 styling conflict with Helix Ultimate

### ISSUE THREAD

**Issue by trainspotting** [JoomShaper/helix-ultimate#243] opened 2021-10-04 11:40 UTC
I reported a significant styling issue to a third party component developer - they researched and identified Helix Ultimate as causing a conflict.. They said...

_For the toolbar buttons: The template implements some override to Joomla core toolbar buttons and it causes the issue. Somehow, the output of the buttons are incorrect, and it causes the issue_

In the image the very colourful section just under the title should be a set of buttons - not all nested up like they all. In default Joomla 4 template they do show properly, but I get this with Ultimate.

![error1](https://user-images.githubusercontent.com/13025180/135845164-103fd9d7-4efd-45b0-83d2-55c936c110af.png)

**Comment by joomdonation** [comment] 2021-11-23 07:50
If anyone is having the issue, here is a quick modification I made for my customer. You can get this zip file, unzip it, upload to folder plugins\system\helixultimate\overrides\layouts\joomla to replace the old code and it should work OK

[toolbar.zip](https://github.com/JoomShaper/helix-ultimate/files/7586456/toolbar.zip)

**Comment by Shorty0811** [comment] 2021-11-23 08:02
Thank you so much Tuan!!! :)

**Comment by ximcix** [comment] 2021-12-04 22:01
Thanks for this fix

**Comment by travelingflwr** [comment] 2021-12-31 17:16
I just tried this and no luck.  Can you expand on what you changed to help me with troubleshooting this?  My site currently has the issue with Helix Ultimate.

**Comment by Shemeam** [comment] 2022-01-10 09:17
As always, way ahead of everyone else, thanks Tuan

**Comment by joomdonation** [comment] 2022-03-16 15:28
It has been few months since the bug was reported. When do you think you can fix this bug @kawshar ? There are some other bugs like:

1. The override for user form field broken (still uses behavior.modal which was removed in Joomla 4)
2. The override for calendar form field (always show time for date picker for some reasons)

**Comment by kawshar** [comment] 2022-03-16 20:02
Informed the team. I hope the issue will be resolved soon.

Thanks

**Comment by kawshar** [comment] 2022-03-16 20:03
> It has been few months since the bug was reported. When do you think you can fix this bug @kawshar ? There are some other bugs like:
> 
> 1. The override for user form field broken (still uses behavior.modal which was removed in Joomla 4)
> 2. The override for calendar form field (always show time for date picker for some reasons)

Informed the team. I hope the issue will be resolved soon.

Thanks

**Comment by Shemeam** [comment] 2022-05-05 09:47
It wasn't fixed in the latest release causing additional work for everyone!!

**Comment by joomdonation** [comment] 2022-05-06 08:05
@kawshar Could we have an update ? Our extensions support frontend management, so we are having this issue with every customers use Helix base templates. Any chance of having this fixed soon ?

**Comment by Shemeam** [comment] 2022-05-20 15:23
I have just upgraded Helix to Version 2.0.9 and it is still not fixed!!!!

**Comment by prakash-a7x** [comment] 2022-05-25 06:25
In the next update this issue will be resolved.
Thank you all for your patience

**Comment by chattigre** [comment] 2022-06-21 16:27
> In the next update this issue will be resolved. Thank you all for your patience
Thanks @prakash-a7x !
When will the next update be available please ? Soon ?

Regards.

**Comment by Shemeam** [comment] 2022-06-22 13:36
@prakash-a7x you have marked this as fixed, but it is not fixed.
Please explain when it will be fixed and when the next release of helixulitmiate with the fix will be available.

**Comment by prakash-a7x** [comment] 2022-06-23 05:31
We will update helix soon, I'm assuming within next week. 
So please be patience.
@Shemeam, yes I've marked as fixed because its been fixed in dev branch...please wait for the update

**Comment by joomdonation** [comment] 2022-06-23 05:36
@prakash-a7x Do you have a testing package which we can try and make sure the issues fixed ? If Yes, I would be happy to test and report back the result. Thanks

**Comment by prakash-a7x** [comment] 2022-06-23 05:44
@joomdonation yes, sure
Please check with this package and let us know if you find any issue related to this thread or even other issue.
Thank you
[helix_ultimate_pkg_2.0.9.zip](https://github.com/JoomShaper/helix-ultimate/files/8964321/helix_ultimate_pkg_2.0.9.zip)

**Comment by joomdonation** [comment] 2022-06-23 05:46
Thanks @prakash-a7x . Will test it and report the result back

**Comment by prakash-a7x** [comment] 2022-06-23 05:47
@joomdonation you are most welcome

**Comment by joomdonation** [comment] 2022-06-24 04:02
@prakash-a7x I tested the package with my extensions and most of the issue is sorted. There is a remaining issue: Bootstrap Dropdown https://getbootstrap.com/docs/5.2/components/dropdowns/ is not working with your template for some reasons

If I replace this line of code https://github.com/JoomShaper/helix-ultimate/blob/master/plugins/system/helixultimate/src/Core/HelixUltimate.php#L354 (for Joomla 4) with HTMLHelper::_('bootstrap.framework'); to load bootstrap js from Joomla core, it is working well

Could you please check to see why Bootstrap Dropdown is not working with your template and get it fixed?

**Comment by prakash-a7x** [comment] 2022-06-24 04:27
> @prakash-a7x I tested the package with my extensions and most of the issue is sorted. There is a remaining issue: Bootstrap Dropdown https://getbootstrap.com/docs/5.2/components/dropdowns/ is not working with your template for some reasons
> 
> If I replace this line of code https://github.com/JoomShaper/helix-ultimate/blob/master/plugins/system/helixultimate/src/Core/HelixUltimate.php#L354 (for Joomla 4) with HTMLHelper::_('bootstrap.framework'); to load bootstrap js from Joomla core, it is working well
> 
> Could you please check to see why Bootstrap Dropdown is not working with your template and get it fixed?

Thanks for your feedback. we will check on the issue

**Comment by joomdonation** [comment] 2022-06-24 04:31
I wonder for Joomla 4 you should load bootstrap script shipped by Joomla instead of load your own bootstrap script ? As of right now, if third party extensions use HTMLHelper::_('bootstrap.framework'); to load bootstrap script, it will result in duplicate bootstrap script loaded (one from Joomla core and one from your own).

**Comment by prakash-a7x** [comment] 2022-06-28 05:44
@joomdonation We are aware of this issue. we are trying for a workaround of this problem.. hopefully in near updates we will resolve the problem. 
Thanks for your comment

**Comment by joomdonation** [comment] 2022-06-28 06:03
Thanks @prakash-a7x . Hopefully it will also be fixed on your next update

**Closed** 2022-08-01 10:06 UTC
Labels: bug, override, Fixed

**Comment by joomleb** [comment] 2023-01-27 20:50
> @prakash-a7x I tested the package with my extensions and most of the issue is sorted. There is a remaining issue: Bootstrap Dropdown https://getbootstrap.com/docs/5.2/components/dropdowns/ is not working with your template for some reasons
> 
> If I replace this line of code https://github.com/JoomShaper/helix-ultimate/blob/master/plugins/system/helixultimate/src/Core/HelixUltimate.php#L354 (for Joomla 4) with HTMLHelper::_('bootstrap.framework'); to load bootstrap js from Joomla core, it is working well
> 
> Could you please check to see why Bootstrap Dropdown is not working with your template and get it fixed?

@joomdonation
As I reported here in detail https://github.com/JoomShaper/helix-ultimate/issues/258#issuecomment-1405329823 I still have back the same Bug.

Are you suggesting to change the line 354 (now 359 in Helix Ultimate 2.0.11) ? :
$this->add_js('bootstrap.bundle.min.js');
with:
HTMLHelper::_('bootstrap.framework');
Am I right ?

Please, What about the line 363 ?!?:
$this->add_js('popper.min.js, bootstrap.min.js');


> ...As of right now, if third party extensions use HTMLHelper::_('bootstrap.framework'); to load bootstrap script,...
@joomdonation
Please, Can you explain me a little bit more ?
Maybe, Is this the reason because I'm having back the strange behavior I mentioned ?

> I wonder for Joomla 4 you should load bootstrap script shipped by Joomla instead of load your own bootstrap script ? As of right now, if third party extensions use HTMLHelper::_('bootstrap.framework'); to load bootstrap script, it will result in duplicate bootstrap script loaded (one from Joomla core and one from your own).

@joomdonation
I'm totally agree, by using Helix Ultimate on top of Joomla 4.x I don't see the need to force overriding of what is standard in Joomla 4.


> @joomdonation We are aware of this issue. we are trying for a workaround of this problem.. hopefully in near updates we will resolve the problem.
Thanks for your comment

@mi-prakash 
Maybe, in first of all, there should be a setting to exclude loading, as was done for "Advanced > Font Settings > Enable Font Awesome". 
Do you agree ?
